# Generated by Django 3.0.5 on 2020-04-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_about_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='aboutme1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='aboutme2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='aboutsite1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='aboutsite2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='bhanai',
            field=models.TextField(),
        ),
    ]
