# Generated by Django 3.0.5 on 2020-04-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200415_0348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
